version: "3"

services:
  server:
    container_name: parrotbot_server
    image: parrotbot:latest
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - parrotbotdb:/server/dbvolume
      - ./server/log:/server/log

volumes:
  parrotbotdb:
