version: "3"

services:
  server:
    container_name: parrotbot-server
    image: parrotbot:latest
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - parrotbotdb:/server/dbvolume
volumes:
  parrotbotdb:
