version: "3"

services:
  server:
    container_name: parrotbot_server
    image: parrotbot:latest
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./server/files/plan:/server/files/plan
      - ./server/files/log:/server/files/log
      - ./server/files/db:/server/files/db
